advcbv/advcbv/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from basic_app import views

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view()),
    url(r'^basic_app/',include('basic_app.urls',namespace = 'basic_app')),
]

advcbv/basic_app/urls.py
from django.conf.urls import url
from basic_app import views


app_name = 'basic_app'
urlpatterns = [
    url(r'^$',views.SchoolListView.as_view(),name='list'),
    url(r'^register/$',views.register,name = 'register'),
    url(r'^(?P<pk>\d+)/$',views.SchoolDetailView.as_view(),name='detail'),
    url(r'^create/$',views.SchoolCreateView.as_view(),name = 'create'),
    url(r'^update/(?P<pk>\d+)/$',views.SchoolUpdateView.as_view(),name='update'),
    url(r'^delete/(?P<pk>\d+)/$',views.SchoolDeleteView.as_view(),name='delete'),
]

advcbv/basic_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    # Create relationship (don't inherit from User!)
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # Add any additional attributes you want
    portfolio_site = models.URLField(blank=True)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option=”build_ext” --global-option=”--disable-jpeg”
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        # Built-in attribute of django.contrib.auth.models.User !
        return self.user.username


# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})



class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveBigIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE) # 可以使student連結school資料
    
    def __str__(self):
        return self.name

advcbv/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.db.models import fields 
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic') 

advcbv/basic_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
# Create your views here.
from . import models
from basic_app.forms import UserForm,UserProfileInfoForm

class IndexView(TemplateView):
    template_name = 'index.html'


def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

        


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School
    


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name','principal','location')#給user改的欄位
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

advcbv/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>
      CBVs
    </title>

    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:list' %}">School</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
        </ul>

    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

advcbv/basic_app/templates/basic_app/login.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block %}

<div class="jumbotron">
    <h1>Please Login</h1>
    <form method="POST" action="{%url 'basic_app:user_login'%}">
        {% csrf_token %}
        
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Username">

        <label for="password"></label>
        <input type="password" name="password">

        <input type="submit" name="" value="Login">

    </form>

</div>

{% endblock %}

advcbv/basic_app/templates/basic_app/registration.html
{% extends "basic_app/basic_app_base.html"%}
{% load static %}
  {% block body_block %}
  <div class="jumbotron">
    
    {% if registered%}
        <h1>Thank you</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>

        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{user_form.as_p}}
            {{profile_form.as_p}}
            <input type="submit" name ='' value="Register">
        </form>
    {% endif %}
  </div>
  {% endblock %}

advcbv/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block %}

<h1>Delete {{school.name}}?</h1>
<form method="post">
    {% csrf_token %}

    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>

</form>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_detail.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block %}

<div class="jumbotron">
    <h1>Welcome to the Scool Detail Page</h1>
     <h2>School detail:</h2>
     <p>Name: {{school_detail.name}}</p>
     <p>Principal: {{school_detail.principal}}</p>
     <p>Location: {{school_detail.location}}</p>
    
    {% for student in school_detail.students.all %} 
      <!-- 抓school裡面的東西 -->
        <p>{{student.name}} who is {{student.age}} years old.</p>
    {% endfor %}

</div>

<div class="container">
  <p><a class = 'btn btn-warning' href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
</div>

{% endblock %}

advcbv/basic_app/templates/basic_app/school_form.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block %}
    <h1>
        {% if not form.instance.pk %}
        Create School
        {% else %}
        Update School
        {% endif %}
    </h1>

        <form method="post">
            {% csrf_token %}
            {{form.as_p}}

            <input type="submit" class="btn btn-primary" value="Submit">

        </form>
    
{% endblock %}

advcbv/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html"%}

{% block body_block %}
    <h1>Welcome to School LIST</h1>
    <ol>
        {% for school in schools %}
            <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
        {% endfor%}
    </ol>
{% endblock %}

advcbv/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>
      CBVs
    </title>

    {# Bootstrap and CSS (Probably would want downloaded files in your real projects)#}
    {# https://bootswatch.com/#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>
  <body>

    <nav class="navbar navbar-default navbar-static-top">
        <ul class="nav navbar-nav">
            <li><a class="navbar-brand" href="{% url 'basic_app:list'%}">School</a></li>
            <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
            <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
        </ul>

    </nav>

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

  </body>

advcbv/templates/index.html
{% extends "base.html" %}

  {% block body_block %}
  <div class="jumbotron">
    <h1>Home page!</h1>
  </div>
  {% endblock %}

advcbv/templates/registration.html
{% extends "base.html" %}
{% load static %}
  {% block body_block %}
  <div class="jumbotron">
    
    {% if registered%}
        <h1>Thank you</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out the form:</h3>

        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{user_form.as_p}}
            {{profile_form.as_p}}
            <input type="submit" name ='' value="Register">
        </form>
    {% endif %}
  </div>
  {% endblock %}